### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by christian-ortmann** [INFO523-S24/project-final-AnalyticalAvengers#1]
The following is the peer review of the project proposal by Daaku Data Singh. The team members that participated in this review are 

- Christian Ortmann:  @christian-ortmann
- Akash Srinivasan: @AkashSrinivasan12
- Rajitha Reddy Tiruthani: @RAJITHAREDDYTIRUTHANI
- Srinivasan Poonkundran: @kANNISTER
- Praveen Kumar Pappala: @Praveen-Kumar-Pappala
- Tejas Bhawari: @tezz-us
-  Gowthan Theeda: @gowthamtheeda

- Describe the goal of the project.

The goal is to analyze how age correlates with dangerous crashes using a January 2024 crash dataset from Massachusetts, with the aim of developing a predictive model to understand and mitigate such incidents.

- Describe the data used or collected.
The data was collected from Massachusetts DOT website.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

They will first focus on human variables like driver demographics then dive into environmental factors such as lighting, weather, and road surface. For this question they will use barplots, scatterplots, and heatmaps.

Their second focus is predictive, they want to use the information from the first part of their analysis to predict the severity of crashes using a classification model such as Logistic Regression, Decision Trees, Random Forests, and Support Vector Machines (SVMs). They will then compare each ML model to determine the best model for this use case.

- Is there anything that is unclear from the proposal?

There is no mention of any feature engineering that night be required for analysis. They also don't mention which categorical variables they hope to encode. There is no mention of feature selection methods or removal of correlated variable.

- Provide constructive feedback on how the team might be able to improve their project.

Breaking up some of the paragraphs into sub headers. Also mention any outside languages you might be using to fine tune the final project. Provide descriptions of each variable.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

The age group most associated with severe crashes, especially very old drivers and and new drivers.

- Provide constructive feedback on any issues with file and/or code organization.

As mentioned before add more headings/sub headings.

- (Optional) Any further comments or feedback?

**Comment by hmfattah** [comment]
Thank you for your valuable feedback. We modified our proposal to discuss about feature engineering, encoding of categorical variables and co-relation analysis. 

Descriptions of each variable are included in the README.md file to keep the main proposal simplified.
