### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by shreemithran** [INFO523-S24/project-final-AnalyticalAvengers#2]
The following is the peer review of the project proposal by Data Detectives. The team members who participated in this review are 

- Shreemithra Naveen - @Shreemithran
- Toluwanimi Olorunnisola - @ToluGb
- Ayesha Khatun - @ayeshakhatunsujana
- Valerie Okine - @valerie-okine
- Alyssa Nether -@rlyalyther
- Abhishek Kumar - @Abhi291712

Describe the goal of the project.

The goal of the project is to analyze how age correlates with dangerous crashes using the January 2024 crash dataset from Massachusetts to develop a predictive model to understand and mitigate such incidents. Another goal is to perform anomaly detection in road safety.

Describe the data used or collected.

* The data is collected from https://apps.impact.dot.state.ma.us/cdv/. 
* This dataset was chosen due to the relevance it holds in today’s day and age which is witness to an unfortunate increase in road accidents in the past 30 years. 
* The dataset is huge with a dimension of 25550 rows and 72 columns; It has 13 numerical variables and 59 categorical variables.

Describe how the research question will be answered, e.g. what approaches/methods will be used.

* Question one analysis plan is to understand those likely to be in a serious crash and the age groups that are mostly at risk for severe crashes.
* Question two analysis plan is to work on predictive modeling of the severity of crashes using some machine learning algorithms. 

Is there anything that is unclear from the proposal?

* Question one doesn't provide the approaches that will be used to determine which age groups are at most risk for dangerous crashes and determine which crashes are more likely to be severe under certain environmental conditions. 
* It is unclear how you intend to deploy your best-performing model to predict the severity of new crashes.
* It is unclear what tool you want to use to build an interactive visualization dashboard.

Provide constructive feedback on how the team might be able to improve their project.

* Could shed more light on high-priority variables and/or variables that may be created using feature engineering techniques.
* Teenagers, Adults, seniors, etc could be used to define the different age categories for question one.
* Question 1 suggests the idea of EDA and the 2nd question follows up with developing predictive models suggesting overlap. Consider thinking about how the data can be further utilized to answer another different question. 
* Describe how you intend to deploy your best-performing machine learning model.
* Since your dataset has 72 columns, consider providing more detailed visualizations that show the different relationships between the categorical and numerical variables.

What aspect of this project are you most interested in and would like to see highlighted in the presentation.

* It would be nice to see some more visualization related to the crash severity and a more in-depth analysis of the crash severity

Provide constructive feedback on any issues with file and/or code organization.

* The organization of your repo looks good. However, you should describe the project organization in your proposal based on the instructions given for Project 2.

(Optional) Any further comments or feedback?

* Good job and all the best with your project!

**Comment by hmfattah** [comment]
Thank you for your detailed feedback on our proposal. 

For determining high-priority variables and those that may be created through feature engineering, we will explore techniques such as correlation analysis and dimensionality reduction to identify key features. 

We acknowledge the need for more detailed visualizations to showcase relationships between categorical and numerical variables given the dataset's size. We will provide comprehensive visualizations that offer insights into these relationships.

We will explore how the data can be leveraged beyond the initial questions posed in the proposal, ensuring that our analysis remains versatile and capable of addressing additional inquiries.
