### ISSUE TITLE
Code peer review

### ISSUE THREAD

**Issue by valerie-okine** [INFO523-S24/project-final-AnalyticalAvengers#4]
The following is the peer review of the project code by Data dectives. The team members who participated in this review are 

Shreemithra Naveen - @shreemithran
Toluwanimi Olorunnisola - @ToluGb
Ayesha Khatun - @ayeshakhatunsujana
Valerie Okine - @valerie-okine
Alyssa Nether -@rlyalyther
Abhishek Kumar - @Abhi291712

#### 1. Purpose of Code
- [X ] Clearly defined and understood
- [ ] Ambiguous or unclear
They used comments in their code which makes their code more readable.
---

#### 2. Code Quality

- [ X] Code is clean, readable, and well-organized
- [X ] Adequate comments explaining complex or tricky code sections
- [ X] Variables, methods, and classes have meaningful names
- [X ] Consistent code style (indentation, naming conventions, etc.)
Good work on the code used for this analysis
---

#### 3. Functionality

- [X ] Code functions as intended and produces the expected outcome
- [X ] Edge cases have been considered and handled
- [X ] No obvious bugs or issues found
For this most of the code functions as is needed however for one of the bar chart visualizations, specifically, the visualization for question 1, the angles at which the labels appear still do not. prevent the texts from looking cramped.
---

#### 4. Testing

- [X ] Adequate unit tests covering key functionality
- [X ] Tests are clear and can be easily understood
- [x ] All tests pass successfully

---

#### 5. Documentation

- [X ] Code documentation (e.g., docstrings, comments) is sufficient
- [ ] Readme or other documentation updated if necessary
The readme file for this group does not say much about the project and should be updated.
---

#### 6. Best Practices

- [X ] No hardcoded values; constants used appropriately
- [X ] Security and privacy concerns addressed (e.g., no sensitive data exposed)
- [ X] Code avoids repetition and promotes reusability

---

#### 7. Additional Comments

- Please provide feedback, areas of improvement, or other observations.

The only issue with the code is that for one of the visualizations in question 1, the code used to take care of the repelling of the labels from each other is not working as needed. The angle should be adjusted in the code to resolve this issue.

#### 8. Recommendation

- [ ] Approved - ready to be merged
- [ X] Approved with minor issues - can be addressed later
- [ ] Requires changes - provide feedback and request another review

---

**Comment by gabegef** [comment]
We appreciate the comments. We have made some revisions to the plots and added some additional comments.
