### ISSUE TITLE
Code peer review

### ISSUE THREAD

**Issue by AkashSrinivasan12** [INFO523-S24/project-final-AnalyticalAvengers#5]
The following is the peer review of the project proposal by Daaku Data Singh. The team members that participated in this review are

Christian Ortmann: @christian-ortmann
Akash Srinivasan: @AkashSrinivasan12
Rajitha Reddy Tiruthani: @RAJITHAREDDYTIRUTHANI
Srinivasan Poonkundran: @kANNISTER
Praveen Kumar Pappala: @Praveen-Kumar-Pappala
Tejas Bhawari: @tezz-us
Gowthan Theeda: @gowthamtheeda
✔️❌
#### 1. Purpose of Code
- [ ✔️ ] Clearly defined and understood
- [ ❌ ] Ambiguous or unclear

---

#### 2. Code Quality

- [ ❌ ] Code is clean, readable, and well-organized
- [ ✔️ ] Adequate comments explaining complex or tricky code sections
- [ ✔️ ] Variables, methods, and classes have meaningful names
- [ ❌ ] Consistent code style (indentation, naming conventions, etc.)

---

#### 3. Functionality

- [ ✔️ ] Code functions as intended and produces the expected outcome
- [ ✔️ ] Edge cases have been considered and handled
- [ ❌ ] No obvious bugs or issues found

---

#### 4. Testing

- [ ✔️ ] Adequate unit tests covering key functionality
- [ ✔️ ] Tests are clear and can be easily understood
- [ ✔️ ] All tests pass successfully

---

#### 5. Documentation

- [ ✔️ ] Code documentation (e.g., docstrings, comments) is sufficient
- [ ❌ ] Readme or other documentation updated if necessary

---

#### 6. Best Practices

- [ ❌ ] No hardcoded values; constants used appropriately
- [ ✔️ ] Security and privacy concerns addressed (e.g., no sensitive data exposed)
- [ ✔️ ] Code avoids repetition and promotes reusability

---

#### 7. Additional Comments

- Please provide feedback, areas of improvement, or other observations.
Readme file is not updated,
Few unorganized code chunks are present,
One whole code chunk was commented  : Testing association between light condition...
Overall Minor changes in the alignments and documentation is required, Good to go.! 
---

#### 8. Recommendation

- [ ] Approved - ready to be merged
- [ ✔️ ] Approved with minor issues - can be addressed later
- [ ] Requires changes - provide feedback and request another review

---

**Comment by gabegef** [comment]
Thank you for your comments. We have added a readme file and made some adjustments so the code is better organized and thoroughly explained
