### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by Praveen-Kumar-Pappala** [INFO523-S24/project-final-AnalyticalAvengers#6]
The following is the peer review of the Presentation proposal by Daaku Data Singh. The team members that participated in this review are 

- Christian Ortmann: @christian-ortmann

- Akash Srinivasan: @AkashSrinivasan12

- Rajitha Reddy Tiruthani: @RAJITHAREDDYTIRUTHANI

- Srinivasan Poonkundran: @kANNISTER

- Praveen Kumar Pappala: @Praveen-Kumar-Pappala

- Tejas Bhawari: @tezz-us

- Gowthan Theeda: @gowthamtheeda

- Content: Is the research question well designed and is the data being used relevant to the research question?

Yes, the research question is well designed and data is relevant.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

The team used many visualizations and each had interpretations.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

The project is carefully thought, there are scopes of improvement which they stated at the end and yes effort went into their project.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

The slides are well organised and good.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

 The team presented very well and professional. Everyone contributed in it.

**Comment by hmfattah** [comment]
Thank you for your feedback!
