### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by rlyalyther** [INFO523-S24/project-final-AnalyticalAvengers#7]
The following is the peer review of the Presentation proposal by [data detectives]. The team members that participated in this review are 

[Ayesha Khatun] - [[@ayeshakhatunsujana](https://github.com/ayeshakhatunsujana)]
[Valerie Okine] - [[@valerie-okine](https://github.com/valerie-okine)]
[Alyssa Nether] - [[@rlyalyther](https://github.com/rlyalyther)]
[Shreemithra Naveen] - [[@shreemithran](https://github.com/shreemithran)]
[Toluwanimi Olorunnisola] - [[@ToluGb](https://github.com/ToluGb)]
[Abhishek Kumar] - [[@Abhi291712](https://github.com/Abhi291712)]

- Content: Is the research question well designed and is the data being used relevant to the research question?

Both research questions are well designed with thought out findings and the data is perfect for the questions.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

Yes, they did a great job using bar plots, heat meats/correlation matrices, ROC curves to visualize their findings and analysis process. The graphs all have interpretations under each visual describing the data well. 

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

Yes, they were very thorough. The team made the effort of going through multiple models to see which one fits the data best / has the highest accuracy. 

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

Yes! All visuals are clean and labeled appropriately. The slides themselves are organized well with correct formatting to create a nice outline when overviewing the slides. 

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

They presented well and had smooth transitions between speakers. Everyone knew what they are talking about when it came to be their turn. They did not reach off of the slides and spoke clearly.

**Comment by hmfattah** [comment]
Thank you for your feedback!
